environment:

  matrix:
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"


install:
    # Make sure pip is around
  - python -m ensurepip
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"


    # Always run commands without asking
  - conda config --set always_yes yes

    # Try to update conda first to avoid odd dependency clashes
  - conda update --all
  - conda install conda-build

    # Create test environment for package
  - conda create -n angstrom_env python=%PYTHON_VERSION% pip pytest pytest-cov numpy
  - activate angstrom_env

    # Install any pip only modules
  - pip install codecov
  - pip install periodictable

    # Build and install package
  - pip install -e .

build: false

test_script:
  - pytest -v --cov=angstrom angstrom\\tests
